//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoTK
    {
        public int MaBC { get; set; }
        public Nullable<int> LoaiBC { get; set; }
        public Nullable<int> MaMH { get; set; }
        public Nullable<int> MaLop { get; set; }
        public Nullable<int> SoLuongDat { get; set; }
        public Nullable<int> HocKy { get; set; }
    
        public virtual Lop Lop { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
