//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public int MaHS { get; set; }
        public int MaMH { get; set; }
        public int HocKy { get; set; }
        public string NienKhoa { get; set; }
        public Nullable<double> Diem15p { get; set; }
        public Nullable<double> Diem1Tiet { get; set; }
        public Nullable<double> DiemCuoiKy { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
